Prepare release v2.8.0
grafana/athena-datasource pull request #223
Opened 2023-03-09 17:28 UTC by kevinwcyu

2023-03-09 18:52 UTC, sarahzinger approved these changes
Nice!

2023-03-10 09:07 UTC, fridgepoet approved these changes

2023-03-10 15:42 UTC, josmperez commented on README.md
> +Note: result reuse requires Athena to be on engine version 3. AWS provides instructions for [Changing Athena engine versions](https://docs.aws.amazon.com/athena/latest/ug/engine-versions-changing.htm
Change "result" to "Result"

2023-03-10 15:42 UTC, josmperez requested changes
A few style edits.

2023-03-10 18:13 UTC, josmperez approved these changes

2023-03-10 18:47 UTC, merged